import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./styles.scss";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function HelloLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <header>BackLinkStudio.com</header>
            <body className={inter.className}>{children}</body>
            <footer>backLinkStudio.com &copy; 2024</footer>
        </html>
    );
}
